### ISSUE TITLE
View metadata on older version of a file

### ISSUE THREAD

**Issue by lmarini** [clowder-framework/clowder2#304] opened 2023-02-01 21:16 UTC
Add ability to view metadata on an older version of a file. Right now both user and extracted metadata tabs are empty when a new version is added.

**Comment by longshuicy** [comment] 2023-02-16 15:19
we need to investigate if we store all the metadata in the mongodb or just replace it with the latest one. @ddey2 could you put what you found here?

**Comment by ddey2** [comment] 2023-02-16 18:00
As far as I am aware, we keep one metadata with every file and keeps on updating the version along with it. 

If a file doesn't have current version metadata, we show the last file version metadata.

**Comment by ddey2** [comment] 2023-02-22 16:23
Expected behavior:
For user metadata - it should show last available version metadata (bug #348 needed to be fixed)
for extractor metadata - it should automatically trigger extractor on updating a file

**Comment by longshuicy** [comment] 2023-04-03 15:46
for user metadata; maybe find a way to associate past file version with past user generated metadata
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/13950475/229560983-ddb20f94-7b65-4191-997d-f31e11911134.png">

**Comment by longshuicy** [comment] 2023-04-03 15:47
For extractor generated metadata;
Differentiate them by versions. Right now it's showing every file version at once
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/13950475/229561272-38d3f6f9-cb58-4270-926f-ccfddf9ab18e.png">

**Comment by arunapa** [comment] 2023-04-13 02:52
I think this was accidentally closed instead of [this issue](https://github.com/clowder-framework/clowder2/issues/376), reopening as it is in progress

**Comment by arunapa** [comment] 2023-04-13 14:24
Elaborating scope of task after hackathon discussion

Expected behavior:
For user metadata - updating a file should update the user metadata, currently updating a file version does not automatically translate the user metadata to the new version.

for extractor metadata - extractor is being triggered automatically on updating file version, but this is not displayed in the UI

**Comment by arunapa** [comment] 2023-04-13 14:25
Also, the UI temporarily flickers with the extractor metadata when a new file version is uploaded. Investigating what's going wrong in the UI.

https://user-images.githubusercontent.com/28983148/231789786-cf301de6-1236-4ec1-89e8-752213d95bc2.mov

**Comment by arunapa** [comment] 2023-04-13 15:13
Logging my observations for user metadata

When a new file version is uploaded, the user metadata is updated in the backend as well, as seen in mongo versions here
<img width="505" alt="Screenshot 2023-04-13 at 10 12 20 AM" src="https://user-images.githubusercontent.com/28983148/231804738-da214a24-0dbd-4de1-a217-67efa531df33.png">

So the issue is that the frontend is not displaying the metadata. And the likely rootcause is because the "description" field of the updated metadata seems to be _null_

**Closed** 2023-04-17 15:44 UTC
Labels: bug, frontend
