### ISSUE TITLE
Updated on not reflected after edits

### ISSUE THREAD

**Issue by FyZoey** [clowder-framework/clowder2#995] opened 2024-04-05 22:55 UTC
<img width="1552" alt="Screenshot 2024-03-25 at 3 16 3" src="https://github.com/clowder-framework/clowder2/assets/65145184/e790acfd-effb-4f2d-a4b5-047672a37ffb">

In this screen, the participant tried multiple editing to the dataset, but the “updated on” is always the same with the “created on” information, please check if this is a bug.

**Comment by longshuicy** [comment] 2024-04-15 14:12
I can't reproduce this bug. 
1. E.g. trying your dataset https://clowder2.software-dev.ncsa.illinois.edu/datasets/6601db3f757c9d702c7a0458
2. Rename, Edit description, as well as change status all results in the "updated on" field changed
<img width="297" alt="image" src="https://github.com/clowder-framework/clowder2/assets/13950475/e5e62837-c9f2-4805-a0e5-9b0e732aa894">

Could you let me know any specific steps I need to follow to reproduce this?

**Comment by FyZoey** [comment] 2024-04-15 20:53
<img width="1920" alt="Screenshot 2024-04-15 at 3 52 39 PM" src="https://github.com/clowder-framework/clowder2/assets/65145184/850b1498-3554-4ed2-91e4-4c1928067c9e">
Sara updated the image file (see the yellow-greenish image, it's showing v2), and the 2 time marks are the same.

**Comment by longshuicy** [comment] 2024-04-15 20:55
Oh changing content of the dataset (e.g. update files) doesn't update the datasets yet. Do we want to implement that feature? @lmarini

**Comment by lmarini** [comment] 2024-06-06 20:52
Should adding files update "updated on?" I think so, right @longshuicy ?

**Comment by lmarini** [comment] 2024-06-20 14:36
Should get fixed by #1026

**Closed** 2024-08-01 14:31 UTC
Labels: bug, user testing
